[build]
  # Build command for client only
  command = "npm run build:client"
  # Publish directory (client files)
  publish = "client/dist"
  # Functions directory
  functions = "netlify/functions"

[build.environment]
  # Set Node.js version
  NODE_VERSION = "18"

# Redirects for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API redirects to Netlify Functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers for static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Headers for HTML files
[[headers]]
  for = "*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Environment variables (you'll need to set these in Netlify dashboard)
[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "preview"

[context.branch-deploy.environment]
  NODE_ENV = "development"
