services:
  # Single Web Service for both Express.js backend and React frontend
  - type: web
    name: sak-planhouse
    env: node
    plan: starter
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: PAYSTACK_SECRET_KEY
        sync: false
      - key: PAYSTACK_PUBLIC_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true

databases:
  # PostgreSQL database
  - name: sak-planhouse-db
    plan: starter
    databaseName: sakplanhouse
    user: sakplanhouse_user
