// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://peixnsayjbsuriidziii.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlaXhuc2F5amJzdXJpaWR6aWlpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMjI1NTQsImV4cCI6MjA3MTg5ODU1NH0.9HB2MLM8duvM3gdzXH3BLZ8XaCp0fQMP6-tWf6jKfao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});